### ISSUE TITLE
Usage for university project

### ISSUE THREAD

**Issue by Fearge** [HUCORP-admin/Pygame-Camera#1]
Hey, 
I'm currently doing a project in uni, where we have to create a game in pygame. Since we want to make a sidescrolling game, your repository woul d be great to use as a starting point for us. We would like to modify the code further on and add features like enemies and attacks. Also the animations and graphics will be replaced with ones created by us.
I didn't find any info on the copyright of your code, so I want to make sure, that it's fine for you if we use it. The project won't be published in any way and we won't make any profit off of it. We will just send it to our teacher for the project to be graded.
Is it fine for you, when we use your code in the described extent?

Greetings from germany

**Comment by HUCORP-admin** [comment]
Hi Fearge, sure feel free to use the code as you like!

**Comment by HUCORP-admin** [comment]
closed
